src/i_main.c
src/m_argv.c
src/m_argv.h
src/m_config.c

I.e. save config file in folder with executable, not in `system32`.

[Windows] Properly open WAD files by "Open with..."

---

src/i_video.c
src/v_trans.c
src/v_trans.h
src/v_video.c

Should be slightly faster:
* Blending function switched to `I_BlendDark`, patch coloring no longer needed.
* Simplified math for shadow positioning.

Simplify and optimize shadowed patch drawing

---

src/d_loop.c
src/d_loop.h
src/doom/m_menu.c

This will fix possible silent crash on toggling resolution/widescreen in options menu while demo playing or network game, i.e. when framerate is not capped even while active menu.

Forcefully supress interpolation in video options menu

---

src/doom/st_bar.c

@fabiangreffrath, @rfomin, @MrAlaux, might be interesting for you ports.
Fabian have fixed «[Status bar face hysteresis](https://doomwiki.org/wiki/Status_bar_face_hysteresis)» bug, but this goes a little bit farther: when player gets hurt, pain or ouch face have higher priority and thus, until pain/ouch tics are active, god face is unable to appear. Typical case to test: save game near invul sphere, make a face-rocket and immediately grab sphere. You will see this (i.e. evil grin in Woof, ouch/pain in Crispy Doom):
The code below fixes it, making god face immediately active once sphere is picked up or `IDDQD` is quickly typed.

Raise invulnerability priority

---

src/doom/g_game.c

This fixes player movement / camera rotation while active menu in multiplayer game or `-solo-net` mode. Seems to be safe for real multiplayer and demo recording/playback while multiplayer.
@fabiangreffrath, @rfomin, might be useful for Woof/Crispy Doom as well, but I have a hunting suspicion that it can be achieved easier or... Safer? Probably via `M_Responder` as Roman suggested, but I have no luck to properly deny mouse events there.

Deny all player control events while active menu in multiplayer

---

src/doom/am_map.c
src/doom/am_map.h
src/doom/d_main.c
src/doom/id_func.c
src/doom/m_menu.c
src/id_vars.c
src/id_vars.h
src/m_config.c

This widget didn't make a final cut in 7.0 release. Not really useful commonly, but pretty nice for demo watching.

Allow to always draw level name

---

src/d_loop.c
src/doom/m_menu.c
src/doom/m_menu.h
src/doom/r_main.c

This should fix possible `R_MapPlane` error while toggling rendering resolution. Previous approach was to cap framerate to 35 fps while in Video Options, but turns out it was not optimal. Not sure what's the _real_ nature of this error, though. 
Many thanks to @MrAlaux for pointing out that it still can happen!

Disable rendering of player view while in Video Options menu

---

src/doom/m_menu.c
src/doom/st_bar.c
src/id_vars.c
src/id_vars.h
src/m_config.c

Now turned off by default, to match up default settings, and can be turned on in Gameplay Features / Status Bar. 
Thanks @OpenRift412 for suggestion!

Make blinking of missing keys optional

---

src/CMakeLists.txt

To fix remaining pedantic warnings under GCC.
Co-Authored-By: Roman Fomin <rfomin@gmail.com>

Separate platform-dependent source files

---

src/i_video.h

This fixes rarely random crashes while column drawing (sprites or 2-s transparent walls) on... game loading. What's the nature of this bug? I don't know. Neither GCC/Clang compilers were giving any possible overflow warnings, nor debuggers were showing any clear points all this time.

Extend MAXWIDTH/HEIGHT arrays

---

src/doom/d_main.c
src/doom/g_game.c
src/doom/g_game.h
src/doom/m_menu.c
src/doom/p_mobj.c
src/doom/s_sound.c

@fabiangreffrath, @rfomin, this is an extremely straightforward implementation, inspired by Woof, but probably slightly different since I wanted to understand how to do this on my own. Interestingly, jumping to the next level feels slightly faster than in Woof, probably because I'm not using `I_FinishUpdate` for the smooth drawing demo bar, but the difference is barely noticeable, it's only about a couple of milliseconds. Could it be useful for Crispy Doom, where these two keys just stop the demo playback?
Few thoughts:
- Function and `demo_nextlevel` boolean names. Not sure they fits well, needs more thinking to make them more consistent with original code.
- Code styling. Needs some polishing as well, especially in `g_game.c` to "mimic" original id Software style, but that's not a big …

Implement reload / go to next level while demo playing

---

src/doom/m_menu.c

Logic as follows:
- Vanilla value: dark red
- Capped value: yellow
- Normal/non-vanilla value: green
- Numbers in Vanilla sound volume menu (`F4`) have only dark coloring if volume is zero, it should remain as vanilla as possible.
- And so on...
Some reasonable exceptions are still here, like vanilla music synth is OPL2, but having green "OFF" for such case feels incorrect.
Thanks @liPillON for heads up in https://github.com/fabiangreffrath/woof/issues/1256!

Improve menu items coloring logic

---

src/d_loop.c
src/d_loop.h
src/doom/am_map.c
src/doom/d_main.c
src/doom/m_menu.c
src/doom/st_bar.c
src/doom/st_bar.h
src/heretic/d_main.c
src/heretic/mn_menu.c
src/heretic/sb_bar.c
src/i_video.c
src/i_video.h

In this PR:
* Support for 5x (1000P) and 6x (1200P) rendering resolutions. Technically, 7x and 8x are working via config-file, but it's an overkill for true color render, so let's have reasonable cap.
* More precise «multiplier correction» and display of current rendering resolution (shamelessly taken from Nugget Doom! 🧡)
* Doom: optimized status bar drawing. Could be much better, but even redrawing every game tic (not every frame) gives huge FPS boost on 6x resolution. Should be useful for smaller resolutions as well.
* Hopefully better fail-safe return in case of active post rendering hook. Now it's able to survive stress-test like drawing extreme scene while holding button for resolution changing in uncapped fps.

Add support for 5x (1000p) and 6x (1200p) rendering resolutions

---

src/doom/am_map.c
src/doom/d_main.c
src/doom/g_game.c
src/doom/m_menu.c
src/doom/r_main.c
src/doom/st_bar.c
src/doom/st_bar.h

This adds back `V_CopyRect` function for drawing background beneath status bar elements. Practically, this costs nothing comparing to (re-)drawing status bar every game/frame tic. This approach inspired by both Doom and Heretic games.

Optimize status bar background drawing

---

src/heretic/d_main.c
src/heretic/doomdef.h
src/heretic/g_game.c
src/heretic/mn_menu.c
src/heretic/p_local.h
src/heretic/p_mobj.c
src/heretic/p_setup.c
src/heretic/s_sound.c
src/heretic/sb_bar.c

To match up Crispy Heretic standards and few extras:
* Parameter `-demoextend` now default, allowing to record/watch longer than one level demo. Non-extended demo also stops while dead player is trying to respawn.
* Demo warp feature (i.e. support for warping like `inter-heretic.exe -playdemo hanoE1SMdemo-522.lmp -warp 1 4`).
* Demo footer with source port name and command line contents, including autoload. Must be a DSDA's established standard. 
* Special keys "Restart demo" and "Go to next level" now working as should while demo playback.
* `IDCLEV`/`ENGAGE` working while demo playback.
* Preventing of overriding demos by adding a file name suffix `-NNNNN`.
* It is possible to pause demo playback.

Heretic: improvements for demo recording/playback

---

src/heretic/CMakeLists.txt
src/heretic/doomdata.h
src/heretic/mn_menu.c
src/heretic/p_local.h
src/heretic/p_maputl.c
src/heretic/p_setup.c
src/heretic/p_sight.c
src/heretic/r_local.h

* Support for DeePBSP and ZDBSP (compressed and uncompressed).
* `BLOCKMAP` recreation if necessary.
* Updated old code of `P_GroupLines` (from Doom 1.2?) with actual one, loading a map with size of Sunder map15 takes not **6** seconds, but just **350** milliseconds.

Heretic: add support for extended nodes + possible BLOCKMAP fix

---

src/heretic/d_main.c
src/heretic/s_sound.c

Using (255 - angle) for the flipped sound angle seems right, and lets you return to using int for the sound angle.
Moving the display update back to being after the sound update avoids many clicks where the first tic of the sound is played at angle 0. This is a bug introduced with commit 862475c.
For an example of the above, try this map without the fix. Move back and fire the hellstaff, many of the shots will click in the left channel only briefly, before going back to the centre channel. Happens more frequently with uncapped framerates.
[hsnd.zip](https://github.com/JNechaevsky/international-doom/files/13891140/hsnd.zip)
I've played a few episodes with this applied now and it fixes *most* of the sound issues. There is still the occasional click towards angle 0, so a more robust fix …

Sound fixes for Heretic's "flipped levels" and "disable render when minimized"

---

src/doom/ct_chat.c
src/doom/d_main.c
src/doom/d_main.h
src/doom/m_menu.c
src/doom/s_sound.c
src/doom/s_sound.h
src/heretic/ct_chat.c
src/heretic/d_main.c
src/heretic/g_game.c
src/heretic/mn_menu.c
src/heretic/s_sound.c
src/heretic/s_sound.h
src/i_input.c
src/i_input.h
src/i_video.c
src/id_vars.c
src/id_vars.h
src/m_config.c
src/v_diskicon.c
src/v_diskicon.h

This will unify identical variables for both games and will prevent appearing of Doom binds in Heretic config and vice versa.

Separate ID-specific binds per games

---

src/heretic/am_map.c
src/heretic/ct_chat.c
src/heretic/d_main.c
src/heretic/doomdef.h
src/heretic/g_game.c
src/heretic/in_lude.c
src/heretic/mn_menu.c
src/heretic/p_user.c
src/heretic/r_draw.c
src/heretic/r_main.c
src/heretic/sb_bar.c

This should fix background of some widgets not being properly updated as well as font's shadows goes to maximum black:
The trick here is not to re-draw whole bezel every game tic or every frame, but instead, operate with buffered copy of bezel which is safe for performance and FPS. Just like it is done in Doom.

Heretic: switch to Doom bezel drawing code

---

src/heretic/mn_menu.c
src/heretic/sb_bar.c
src/id_vars.c
src/id_vars.h
src/m_config.c

Closes #45 
Things for you to check/decide on:
- Line lengths, variable lengths, general formatting. [This line](https://github.com/JNechaevsky/international-doom/commit/8332db94e6cc2b5037f393d1b8d1e3628cad30c8#diff-ebca5aac746b7e31419da0d1099371152b08942d1bb47b7a554cd4e716b7dfa0R3137) is ugly but I don't know your preference for extending the whole table.
- The name "ammo widget coloring" is kind of confusing since the weapon letters are colored even when it's off, but there's only so much room to type. "Extend widget colors" maybe?
- I put in multiple options for coloring the ammo/weapons but maybe you want it just on/off.
- SB_AmmoWidgetColor could be broken into two functions
Thanks!

Heretic: colored ammo widget

---

src/heretic/p_local.h
src/heretic/p_map.c
src/heretic/p_mobj.c

This is complex fix:
- Hitscan puffs now able to appear on floor/ceiling, even when bumped in front of back side 2-sided line (🤯...).
- Missile explosions no longer disappears on back sides to 2-sided lines, Phoenix Rod explosions are having just a visual effect in such cases.
- Safe for longest full 1-5 episode runs demos, but I still want to check it manually in the game.
- As small diff as possible.

Heretic: fix hitscan/missile puffs disappearing in certain areas

---

src/heretic/am_map.c
src/heretic/mn_menu.c

This will restore proper original automap colors antialiasing and make it more decent. Unfortunately, this approach is less mod-compatible as it relies on original `PLAYPAL`. Extra color fine-tuning is still needed.

Heretic: revert automap code to tablified approach

---

src/doom/m_menu.c
src/doom/r_draw.c
src/heretic/mn_menu.c
src/heretic/r_draw.c

Allocate the buffer according to the actual screen size, not the maximum (quite huge) possible one. Also, there is no need to call `R_SetViewSize()` if the screen size does not actually change.
Fixes `zone memory: ...., 40 (and then) 80 MiB allocated for zone.` case when using bordered screen size.

Reduce zone memory consumption by screen border

---

src/heretic/am_map.c
src/heretic/am_map.h
src/heretic/g_game.c

* Apply antialiasing for green (items), yellow (gasbags) and red (monsters) `IDDT` triangles for better visibility.
* Slightly simplified ReMood-inspired pulse. Not looking very good in non-overlayed background.
* Small cleanup and code simplification.

Heretic: more automap improvements

---

src/heretic/r_plane.c

inter-heretic already has x and y offsets on flats for interpolated scrolling (via Crispy). Using these for drawing all scrolling flats means any flat can scroll, and in any direction, without visual errors.

Heretic: improve flat scrolling animations

---

src/doom/r_data.c
src/heretic/r_data.c

This is have to be done only once at program startup, as HSV tables are not related to colormaps and gamma correction.
Little optimization to save about `5` milliseconds on gamma-correction and few other features toggling.

Call HSV colors initialization only once

---

src/heretic/r_bmaps.c

The stem of the torch uses a colour included in the 'flame' brightmap on a few pixels, and it looks funny in the dark. The head of the torch uses this colour too but it still doesn't look too bad when it's excluded from the brightmap.

Heretic: custom brightmap for serpent torch

---

src/heretic/r_bmaps.c

oops. I guess this isn't technically necessary, but for consistency.

Heretic: missing break from serpent torch brightmap

---

src/hexen/h2def.h
src/hexen/info.c
src/hexen/mn_menu.c
src/hexen/r_draw.c
src/hexen/r_local.h
src/hexen/r_main.c
src/hexen/r_things.c

Same to Heretic, this makes previously opaque sprites translucent. There is probably some potential for extra object left, but it need normal playtesting.

Hexen: Extra Translucency feature

---

src/hexen/am_map.c
src/hexen/am_map.h

- Better smoothing in overlay mode.
- All line types now smoothed.
- `IDDT` (oops, `MAPSCO`) extended colors.

Hexen: automap lines revisited

---

src/doom/m_menu.c
src/heretic/mn_menu.c
src/hexen/mn_menu.c

- Allowed darker values, same to automap background shading.
- Shading disabled for one second while changing gamma or saturation/intensity to see changes.
- Simplified `M_ShadeBackground` calls .

Background shading revisited

---

src/hexen/h2def.h
src/hexen/mn_menu.c
src/hexen/p_pspr.c
src/hexen/r_things.c
src/hexen/s_sound.c
src/hexen/sb_bar.c
src/hexen/sv_save.c
src/id_vars.c
src/id_vars.h
src/m_config.c

* Class-based armor: now default. Original port settings is matching up vanilla executable, and generic icon is not really vanilla. In other words, this is a Right Thing to do.
* SFX attenuation axises: not that epic as in Doom and Heretic, it works only for monsters and thing-type map objects, i.e. not doors, sectors, platforms, etc.. Hexen handles sectors slightly differently, but even attenuation for thing-type only seems to be okay.
Weapon attack alignment removed entirely, it's working only with half of weapons. 🙁 That's because of Hexen's "extra" coords shifting for some frames, i.e. weapon state can be same to prevent extra sprite graphics, but may have different offset.

Hexen: class-based armor and sfx attenuation features

---

src/v_video.c

Now for all sides, not just bottom. Could be a little bit simpler, but okay.

Prevent frame buffer overflow for "shadowed" patch drawing functions

---

src/doom/d_main.c
src/doom/g_game.c
src/heretic/am_map.h
src/heretic/d_main.c
src/heretic/g_game.c
src/heretic/s_sound.c
src/hexen/am_map.h
src/hexen/d_net.c
src/hexen/g_game.c
src/hexen/h2_main.c
src/hexen/sb_bar.c

Initially was planned for Hexen only, but other games gets improvements as well:
* All games: chosen by `F12` player now kept between level changes while multiplayer demo playback. No need to change player over and over again on every level change (probably could be useful for Woof and Crispy, if @fabiangreffrath and @rfomin will be interested?)
* Heretic: better toggling, notably automap showing correct player arrow angle on overlay mode.
* Hexen: full implementation.
* Heretic and Hexen: messages now showing correctly for chosen by `F12` player.
TODO for later:
* Heretic showing incorrect player arrow color in multiplayer. Will fix after @kitchen-ace's improved secret sectors handling, so we don't have a possible diff issues.

Heretic and Hexen: upgrade spy mode

---

src/heretic/am_map.c

Order is now:
* ML_DONTDRAW, unless map cheat is on
* ML_SECRET (draw as 1-sided), except secret sectors
* keyed doors
* exits, now including 2-sided switch exits
* teleporters
* secret sectors, if option is enabled
* normal drawing
fixes #103

Heretic: fix priority of automap linedef coloring

---

src/doom/d_main.c
src/heretic/d_main.c
src/hexen/h2_main.c
src/m_config.c
src/m_config.h

Needs some polishing. Probably worth to make `D_SetDefaultSavePath` global for all three games, but it's slightly different for Hexen.
Fixes #125, thanks @liPillON for suggestion!

Add `savegames_path`, `screenshots_path` config variables and `-shotdir` parameter

---

src/doom/m_menu.c
src/heretic/mn_menu.c
src/hexen/mn_menu.c

Fixes following case:
* Cursor is placed on any kind of menu items.
* Left mouse button is clicked and being held.
* While button holding, horizontal and/or vertical mouse movement will be registered as button pressing and thus, will activate menu item again while movement.

Menu: do not consider mouse movement as button pressing

---

src/doom/f_wipe.c
src/doom/r_data.c
src/doom/r_draw.c
src/heretic/f_wipe.c
src/heretic/r_data.c
src/heretic/r_draw.c
src/hexen/f_wipe.c
src/hexen/r_draw.c

Not exactly _optimizations_, just a little bit of _de-consumption_. This does the following:
* Screen wipe effect. Needs allocated memory to perform, but once done, no need to hold it as a purgable hostage.
* Screen border. Mostly the same as above.
But in the end all this is a matter of 2-15 megabytes, depending on the rendering resolution.

Small memory optimizations

---

src/doom/p_inter.c
src/doom/p_local.h
src/doom/p_user.c
src/doom/st_bar.c
src/heretic/p_enemy.c
src/heretic/p_inter.c
src/heretic/p_local.h
src/heretic/p_user.c
src/heretic/sb_bar.c
src/hexen/p_enemy.c
src/hexen/p_inter.c
src/hexen/p_local.h
src/hexen/p_user.c
src/hexen/sb_bar.c
src/i_video.c

* No need to perform pane alpha value operations over the game state code. Let the gametic-based palette handler calculate it and pass it to the renderer.
* Such approach should be more accurate, comparing to original one.

Rewrote and simplify smooth palette changing

---

src/hexen/g_game.c
src/hexen/h2def.h
src/hexen/mn_menu.c
src/hexen/p_mobj.c
src/hexen/p_pspr.c
src/hexen/p_user.c
src/hexen/sb_bar.c
src/i_video.c
src/i_video.h

For Smooth Palette Fading feature. Ideally to save `graycount` and `orngcount` in the save game, but this will break compatibility with current save files.

Hexen: smooth palette fading for Wraithwerge and Bloodscourge

---

src/heretic/s_sound.c
src/hexen/s_sound.c

Fix buffer overflow below in Heretic and Hexem when `S_StartSound` is called with NULL parameter and the static listener is used. Trivially happens when no level is started and pressing ESC to display the menu
```
=================================================================
==283421==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000000952b20 at pc 0x00000057193f bp 0x7ffc08032960 sp 0x7ffc08032958
READ of size 8 at 0x000000952b20 thread T0
#0 0x00000057193e in S_StartSoundAtVolume /home/bobbie/git_projects/international-doom/src/hexen/s_sound.c:354
#1 0x00000057145e in S_StartSound /home/bobbie/git_projects/international-doom/src/hexen/s_sound.c:251
#2 0x0000004aa97c in MN_ActivateMenu /home/bobbie/git_projects/international-doom/src/hexen/mn_menu.c:6673
#3 …
```

Heretic, Hexen: fix buffer overflow when playing sounds in some cases
