- src/doom/m_menu.c
- src/doom/r_data.c
- src/doom/r_things.c
- src/i_video.c
- src/v_trans.h
Between:
- Additive. Current bright implementation
-  Blending. More or less _classical_ look.
> Allow to choose translucency style

- src/doom/m_menu.c
- src/doom/r_draw.c
- src/doom/r_local.h
- src/doom/r_main.c
- src/doom/r_things.c
- src/i_video.c
- src/v_trans.h
True color translucency is giving absolutely nice results, so why not to use in full power?
> Add translucent style for fuzz effect

- src/doom/am_map.c
- src/doom/d_main.c
- src/doom/m_menu.c
- src/doom/m_menu.h
- src/doom/r_draw.c
- src/doom/r_main.c
- src/doom/st_bar.c
- src/i_video.c
- src/i_video.h
- src/v_video.c
This will fix remaining possible silent crashes or errors while toggling various render functions. Framerare capping or background filling in video menu no longer needed.
> Add post rendering hook function

- src/heretic/mn_menu.c
Readability and simplification, just like done in Hexen.
> Heretic: switch menu item types from `boolean` to `void`

- src/heretic/d_net.c
- src/heretic/doomdef.h
- src/heretic/g_game.c
- src/heretic/id_func.c
- src/heretic/id_func.h
- src/heretic/p_local.h
- src/heretic/p_user.c
- src/heretic/r_main.c
- src/heretic/s_sound.c
- src/heretic/sb_bar.c
- src/heretic/sb_bar.h
* Frags widget now working.
* Fixed non-working blue and red player color translations.
* Improved coop spy (see other player values, health gem and hear their sounds).
* Fixed non-working "player № left the game" message.
> Heretic: various multiplayer improvements

- src/hexen/p_local.h
- src/hexen/p_maputl.c
- src/hexen/p_sight.c
- src/hexen/r_bsp.c
- src/hexen/r_local.h
- src/hexen/r_main.c
- src/hexen/r_plane.c
- src/hexen/r_segs.c
- src/hexen/r_things.c
This adds:
- Removed limits of openings, visplanes, drawsegs and intercepts.
- Visplane hash function.
- Improved clipping of "solid columns" (better visibility blocking by soldid wall columns).
> Hexen: the rest of render optimizations

- src/hexen/p_anim.c
- src/hexen/r_plane.c
This is my old _magical_ implementation, but probably it can be improved or simplified. Things a bit more complicated when we have to scroll texture not via it's offsets, but via column drawing shifting instead.
> Hexen: interpolate sky scrolling

- src/heretic/r_plane.c
- src/hexen/r_plane.c
Straight from Doom, where it's more compact and slightly better polished. This should take care of https://github.com/JNechaevsky/international-doom/issues/77.
> Heretic and Hexen: update visplanes drawing code

- src/doom/m_menu.c
- src/heretic/doomdef.h
- src/heretic/mn_menu.c
- src/hexen/h2def.h
- src/hexen/mn_menu.c
Looks pretty decent so far, and it's mod-compatible. TODOs:
> Apply highlighting/fading to vanilla menu

- src/doom/doomstat.h
- src/doom/g_game.c
- src/doom/m_menu.c
- src/doom/p_user.c
- src/heretic/doomdef.h
- src/heretic/g_game.c
- src/heretic/mn_menu.c
- src/heretic/p_user.c
- src/hexen/g_game.c
- src/hexen/h2def.h
- src/hexen/mn_menu.c
- src/hexen/p_user.c
- src/hexen/sv_save.c
- src/id_vars.c
- src/id_vars.h
- src/m_config.c
Mostly taken from Crispy Doom and Woof.
> Doom & Heretic: implement "On Death Action" feature

- src/doom/d_main.c
- src/heretic/d_main.c
- src/hexen/h2_main.c
Fixes crash at startup under Linux for Hexen.
> Set screenshot folder after config loading

- src/doom/doomdef.h
- src/doom/p_mobj.c
- src/doom/p_saveg.c
- src/doom/r_things.c
Fixes https://github.com/JNechaevsky/international-doom/issues/109
Co-authored-by: Meerschweinmann <116672360+Meerschweinmann@users.noreply.github.com>
> Doom: don't change powerups health for demo sync

- src/heretic/sb_bar.c
> Heretic: add my name to ammo widget func

- src/hexen/CMakeLists.txt
- src/hexen/f_wipe.c
- src/hexen/f_wipe.h
- src/hexen/g_game.c
- src/hexen/h2_main.c
- src/hexen/h2def.h
- src/hexen/mn_menu.c
- src/hexen/r_main.c
- src/id_vars.c
> Hexen: add "Crossfade" screen wiping effect

- src/heretic/d_main.c
- src/heretic/doomdef.h
- src/heretic/mn_menu.c
- src/heretic/r_data.c
- src/id_vars.c
AFAIR, it was disabled while porting CRL to Inter, but no need to keep it as a dead code now.
> Heretic: add back graphical startup

- src/doom/m_menu.c
- src/doom/p_inter.c
- src/doom/p_user.c
- src/doom/st_bar.c
- src/heretic/mn_menu.c
- src/heretic/p_enemy.c
- src/heretic/p_inter.c
- src/heretic/p_local.h
- src/heretic/p_user.c
- src/heretic/sb_bar.c
- src/hexen/mn_menu.c
- src/hexen/p_enemy.c
- src/hexen/p_inter.c
- src/hexen/p_local.h
- src/hexen/p_user.c
- src/hexen/sb_bar.c
- src/i_video.c
- src/i_video.h
- src/id_vars.c
- src/id_vars.h
- src/m_config.c
Pretty simple implementation, but will not work for palette-only engines.
https://github.com/user-attachments/assets/9c07dc95-8764-4c6a-b64a-8ae4ceecbe2b
> Implement smooth red/yellow palette fading

- src/doom/d_main.c
- src/doom/m_menu.c
- src/heretic/d_main.c
- src/heretic/mn_menu.c
- src/hexen/h2_main.c
- src/hexen/mn_menu.c
- src/id_vars.c
- src/id_vars.h
- src/m_config.c
For .wad and .deh files (not lumps!). Allow to choose autoload options:
* Off (disable autoload)
* IWAD only (current and default behavior)
* IWAD and PWAD (create all the folders)
Thanks @Meerschweinmann for suggestion!
> Implement selective autoload

- src/doom/m_menu.c
- src/doom/st_bar.c
- src/heretic/mn_menu.c
- src/heretic/sb_bar.c
- src/hexen/mn_menu.c
- src/hexen/sb_bar.c
- src/i_video.c
- src/id_vars.c
- src/id_vars.h
- src/m_config.c
Not just ON/OFF, use default/halved/quartered/off instead.
> A11Y - implement variable palette flash effects

- src/doom/r_draw.c
- src/doom/r_main.c
- src/doom/r_plane.c
- src/doom/r_segs.c
- src/doom/r_things.c
- src/heretic/r_draw.c
- src/heretic/r_main.c
- src/heretic/r_plane.c
- src/heretic/r_segs.c
- src/heretic/r_things.c
- src/hexen/r_draw.c
- src/hexen/r_main.c
- src/hexen/r_plane.c
- src/hexen/r_segs.c
- src/hexen/r_things.c
Mostly cosmetic, but using local copies of global variables before processing in `for` loops actually makes sense, at least on GCC compiler.
> Small reformat and update for drawing functions

- .github/workflows/main.yml
- CMakeLists.txt
- src/doom/id_func.c
https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache
Kind thanks to @rfomin!
> Set up a vcpkg binary cache using GitHub Actions Cache

- src/heretic/s_sound.c
- src/hexen/s_sound.c
fix regression introduced in PR #203
> Heretic, Hexen: fix some sounds not playing fully
